name: Tests

on:
    pull_request:
        branches:
            - main
            - develop
    push:
        branches:
            - main
            - develop
jobs:
    unit_tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - name: Setup dotnet
              uses: actions/setup-dotnet@v4
              with:
                  dotet-version: '8.0.x'
            
            - name: Restore dependencies
              run: dotnet restore

            - name: Run unit tests
              run: dotnet test --no-restore --verbosity normal